<div align="left"> 
<!--  <h2>PLUG Frequently Asked Questions</h2> -->
<!--  <table width="95%" border="0" cellspacing="0" cellpadding="0"> -->
<!--    <tr>  -->
<!--      <td> -->
    <a name="top"></a> 
        <ol>
          <li><a href="#linux">What is Linux?</a></li>
          <li><a href="#why">Why should I run Linux?</a></li>
          <li><a href="#where">Where can I get Linux?</a></li>
          <li><a href="#plug">What is the Portland Linux Unix Group (PLUG)?</a></li>
          <li><a href="#meetings">When and where are your meetings?</a></li>
          <li><a href="#list">What are the <i>plug</i> and <i>plug-announce</i> 
            e-mail lists and how can I join?</a></li>
          <li><a href="#otherlists">What other e-mail lists does PLUG host?</a></li>
          <li><a href="#archives">How can I search the archives of the <em>plug</em> 
            e-mail list?</a> 
          <li><a href="#clinic">What is the <em>PLUG Linux Clinic</em>?</a></li>
<!--      <li><a href="#lan">What is <em>Linux At Night (LAN)</em>?</a></li> -->
          <li><a href="#k-12">What is <em>PLUG for Education</em>?</a></li>
	  <li><a href="#munging">Why are all of email addresses on the PLUG web site
	  in this odd format? How do I convert them to a useable address?</a></li>
          <li><a href="#microsharp">Who hosts PLUG's Web site?</a></li>
        </ol>
        <a name="linux"></a> 
        <h4>1. What is Linux?</h4>
        <p>Linux is an operating system kernel initially created in 1991 by Linus 
          Torvalds (then a graduate student at the University of Helsinki in Finland). 
          The kernel acts as mediator for your programs (processes) and for your 
          hardware. It takes care of memory management for all running processes, 
          giving them access to processor cycles. The kernel also provides a portable 
          interface for processes to talk to your hardware. 
        <p>The Linux kernel was not particularly useful in and of itself -- to 
          be a fully functional operating system it needed a lot of programs such 
          as compilers, editors, and text formatters. It just so happened that 
          the <a href="http://www.fsf.org/" target="_blank">Free Software Foundation 
          (FSF)</a> had been undergoing a massive effort (since 1983) to develop 
          an operating system called GNU's Not Unix (GNU). By 1991, FSF had developed 
          everything needed for an operating system except for the kernel. 
        <p>In 1991, Linus combined the Linus kernel with the GNU System and finally 
          the world had a 100% <a href="http://www.fsf.org/philosophy/free-sw.html" target="_blank">free</a> 
          operating system. Both the GNU System and the Linux kernel were released 
          under the GNU General Public License (usually called the GPL). The GPL 
          is a &quot;free&quot; software license; this means free in the sense 
          of liberty not in the sense of price (think free speech not free beer). 
          It gives you the freedom to &quot;copy, distribute, study, change, and 
          improve the software&quot;. 
        <p><em>Although PLUG has chosen to refer to the GNU/Linux operating system 
          by the commonly accepted naming convention of Linux, we honor the fundamentally 
          important work that GNU has contributed.</em></p>
        <div align="center"><a href="#top">[Back to top]</a></div>
        <a name="why"></a> 
        <h4>2. Why should I run Linux?</h4>
        <p>There are many reasons to run Linux many of which you will discover 
          as you use it. 
        <p>But some of the most important reasons to run Linux are because it 
          is free, relatively secure, cost-effective, and fun. 
        <ul>
          <li>Linux is free meaning that you have the freedom to &quot;copy, distribute, 
            study, change and improve the software&quot;. </li>
          <li>Linux is relatively secure, in part, because user-space is separate 
            from the kernel preventing malicious code (e.g., a virus) from damaging 
            the kernel.</li>
          <li>Linux is stable often running for months, or even years, at a time 
            without crashing.</li>
          <li>Linux is fun because once you get through the initial learning curve 
            you will realize how much fun it can be to have almost total control 
            over your system.</li>
        </ul>
        <p>While Linux is making inroads on the desktop and has attractive windowing 
          systems available, its primary claim to fame is as a server OS. Linux 
          -- running the Apache web server software -- is the most popular OS 
          for web servers. Check out <a href="../../html/faq/www.netcraft.com" target="_blank">Netcraft</a> 
          to learn more about web servers currently serving the Web.</p>
        <p align="center"><a href="#top">[Back to top]</a></p>
        <a name="where"></a> 
        <h4><b>3. Where can I get Linux?</b></h4>
        <p>Although Linux is free, most users purchase a distribution whereby 
          a distribution company bundles the Linux kernel, GNU software, other 
          software, documentation, etc., together to form a distribution. You 
          can purchase a distribution CD at most computer stores or you can download 
          it for free from most distribution company's Web sites. There are a 
          number of distributions but beginners usually choose <a href="http://www.redhat.com" target="_blank">Red 
          Hat</a> or <a href="../../html/faq/www.linux-mandrake.com" target="_blank">Mandrake</a>. 
          For a more comprehensive list of distributions please see this <a href="http://www.linux.org/dist/english.html">list</a>. 
        </p>
        <div align="center"><a href="#top">[Back to top]</a></div>
        <a name="plug"></a> 
        <h4>4. What is the Portland Linux UNIX Group (PLUG)?</h4>
        <p> We are a community of Linux and UNIX enthusiasts dedicated to teaching 
          and learning about Linux and UNIX. Whether you are a novice or an expert, 
          we welcome you to participate in our e-mail discussion list and to in 
          our meetings and events. We don't have any formal membrship process 
          or membership dues. 
        <div align="center"> 
          <p><a href="#top">[Back to top]</a></p>
        </div>
        <a name="meetings"></a> 
        <h4>5. When and where are your meetings?</h4>
        <p> We hold meetings at 7:00 PM on the first Thursday of every month in 
          Room 296/298, Smith Memorial Center, <a href="http://www.pdx.edu">Portland
	  State University.</a>
        <p> Meetings usually include a few minutes of group business, followed 
          by a speaker. The speaker normally presents for about one-half hour 
          followed by a question and answer session. The speakers are usually 
          experts in some topic of interest to Linux users (e.g., security). If 
          you want to learn about Linux, we highly recommend you attend these 
          meetings. We announce the meetings to <i>plug</i> and <i>plug-announce</i> 
          several days in advance. 
        <p>After the official meeting most people go to the <a href="http://www.luckylab.com/" target="_blank">Lucky 
          Labrador</a> pub for beer and conversation. 
        <div align="center"> 
          <p><a href="#top">[Back to top]</a></p>
        </div>
        <a name="list"></a> 
        <h4>6. What are the <i>plug</i> and <i>plug-announce</i> e-mail lists 
          and how do I join?</h4>
        <p> Through the <i>plug</i> e-mail list we help each other make better 
          use of Linux at home and at work. If you are interested in learning 
          more about Linux we recommend that you subscribe to the e-mail discussion 
          list. Please note that the <i>plug</i> list includes a lot of discussion 
          hence a large volume of e-mail. If you just want to receive just announcements 
          of meetings and other events, then join the <i>plug-announce </i>e-mail 
          list. Please go to <a href="../../html/mailing_list">here</a> to subscribe 
          to or unsubscribe from either list. 
        <div align="center"> 
          <p><a href="#top">[Back to top]</a></p>
        </div>
        <a name="otherlists"></a> 
        <h4>7. What other e-mail lists does PLUG host?</h4>
        <p>We have a number of other e-mail lists covering a variety of topics. 
          Please go <a href="../../html/mailing_list">here</a> for a complete 
          list and to subscribe to or unsubscribe from any of our e-mail lists.</p>
        <div align="center"><a href="#top">[Back to top]</a></div>
        <a name="archives"></a> 
        <h4>8. How can I search the <em>plug</em> e-mail list archives?</h4>
        <p> If you have a question about Linux, changes are good that PLUG members 
          have answered it. Go <a href="http://plug.skylab.org/">here</a> to search 
          the <i>plug</i> list archives. 
        <div align="center"> 
          <p><a href="#top">[Back to top]</a></p>
        </div>
        <a name="clinic"></a> 
        <h4>9. What is the PLUG Linux Clinic?</h4>
        <p> The PLUG Linux Clinic provides an opportunity for you to get hands-on 
          help with your system. If you are more experienced, it provides you 
          an opportunity to help others with their systems. Those needing help 
          can bring their systems to the clinic. 
        <p>We hold the clinics on the <em>third</em> Saturday of the month at 
          Riverdale Elementary School. The coordinator of this event usually sends 
          an announcement to <em>plug</em> and <em>plug-announce</em> during the 
          week prior to the clinic. 
        <div align="center"><a href="#top">[Back to top]</a></div>
        <a name="k-12"></a> 
        <h4>10. What is PLUG for Education?</h4>
        <p> <em>PLUG for Education</em> is an effort by PLUG members to assist 
          K-12 schools in implementing Linux servers and workstations. Monthly 
          events usually coincide with the <em>Portland Linux Clinic</em>. Please 
          see the <a href="http://www.riverdale.k12.or.us/linux/" target="_blank">PLUG 
          for Education</a> Web site for more information. 
        <div align="center"> 
          <p><a href="#top">[Back to top]</a></p>
        </div>
	<a name="munging"</a>
	<h4>11.Why are all of email addresses on the PLUG web site in this odd format?
	How do I convert them to a useable address?</h4>
	<p>Due to the abuse of email commonly known as spamming, the Webmaster has 
	performed a simple form of munging to every email address on this website. So far,
	no one has complained about this step, so the Webmaster will continue this policy
	until either someone does complain, or he is replaced.
<!--    <p>Some people are under the impression that if the Webmaster is presented with
	pairs of hands chopped off of 100 spammers, he will unmunge all of the email 
	addresses on the website. While the Webmaster has never stated this, he
	is willing to accept a gift like this to see if it might convince him to change
	his policy. -->
	<p>A useable email address may be created from the munged one by substituting
	" AT " with &#064;, and " DOT " with .
	<div align="center">
        <p><a href="#top">[Back to top]</a></p>
        </div>
        <a name="microsharp"></a> 
        <h4>12. Who hosts PLUG's Web site and e-mail lists?</h4>
        <p> <a href="http://www.microsharp.com" target="_blank">Micro Sharp</a> 
          has been kind enough to host both PLUG's Web site and e-mail lists. 
          Thank you Micro Sharp! 
        <div align="center"> 
          <p>&nbsp;</p>
          <p><a href="#top">[Back to top]</a></p>
        </div>
<!--      </td> -->
<!--    </tr> -->
<!--  </table> -->
  <hr>
<!--  <p><font size="-1">If you have questions or comments about this FAQ please
e-mail Neil Anuskiewicz at <a href="mailto:">neil@pacifier.com</a>.</font></p> --!>
</div>
